version: 2.1
jobs:
  build-and-push:
    machine: true
    steps:
      - checkout
      #build
      - run: |
          docker build -t jaikumarm/iqfeed:v62025-w8 -f Dockerfile . | cat # workaround progress bar weirdness
      #push
      - run: |
          set -x
          sh +x -c 'echo $DOCKER_PASS' | docker login -u=$DOCKER_USER --password-stdin
          docker push jaikumarm/iqfeed:v62025-w10
          docker tag jaikumarm/iqfeed:v62025-w10 jaikumarm/iqfeed:latest
          docker push jaikumarm/iqfeed:latest

workflows:
  version: 2
  build-and-push-image:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
